[SETTINGS]
UninstallKey  = {924EAD66-F854-4605-8493-696DD59A113B}
GameExe       = RCT.exe

; The following are paths, relative to the DEFAULT.INI's directory.
; AUTORUN.EXE looks for the DEFAULT.INI in it's own directory first. If it does
; not find it there, it looks for a subdir named AUTORUN and checks there.

Readme           = ..\README.TXT
Manual           = ..\Manual\RCTDeluxe.pdf
GameInstaller    = ..\Setup.exe
AcrobatInstaller = ..\Manual\AcroReader51_ENU.exe

; the directory were the string files (english.str, ect.) are located
StringFiles  = .
LangDlgIni   = .\LANGUAGE.INI
ShowLangDlg  = NO
TileBgBitmap = NO

;BgMusic	     = ART\bgMusic.wav

; BITMAPS
BmpSmallFont = ART\Text.bmp
BmpWndBg     = ART\WndBg.bmp
BmpBtnInst   = ART\btnInst.bmp
BmpBtnPlay   = ART\btnPlay.bmp
BmpBtnManl   = ART\btnManl.bmp
BmpBtnRead   = ART\btnRead.bmp
BmpBtnExit   = ART\btnExit.bmp

; REGION DATA
RgnWndBg  = ART\WndBg.rgn

; SOUND
WaveBtnRollOver = ART\RollOver.wav
WaveBtnClickIn  = ART\ClickIn.wav
WaveBtnClickOut = ART\ClickOut.wav

; BUTTON POSITIONS
BtnInstall = 169, 343
BtnReadMe  = 269, 343
BtnManual  = 369, 343
BtnExit    = 575, 380

EEGG	= 323, 87

; STATUS TEXT POSITION
StatusPos = 323, 450



